# photo-viewer-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: photo-viewer-pod
spec:
  containers:
    - name: photo-viewer
      image: ghcr.io/aaronzsam101/aviation-photo-viewer:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
      env:
        - name: PHOTOS_DIR
          value: /photos
        - name: PORT
          value: "3000"
        - name: HOST
          value: 0.0.0.0
        - name: READ_ONLY
          value: "true"
      volumeMounts:
        - name: photos-volume
          mountPath: /photos

  volumes:
    - name: photos-volume
      hostPath:
        path: /Users/aaronliu/Library/CloudStorage/SynologyDrive-MBA-Aaron/Photos/Aviation
